
root_dir: "."
csv_file: "hw_stat_2018.csv"
filters:
    #WallDurationSeconds: [1000, 1100]
    NumberCPU: [12, 12]
    Nodes: [2, 2]
    QueueName: ["infi"]
plot_name: "WallDurationSeconds"
dest_path: "./graph"
tables_path: "./tables"
x_scale: 1


